apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "task-service.fullname" . }}
  labels: {{- include "task-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  {{- /* On real AWS the IRSA role annotation goes here. */}}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false   # the app never calls the API server
